@startuml

rectangle Frontend {
    [Screens]
    [Services]
}

rectangle Backend {
    [FlightModule]
    [BillingModule]
    [BookingModule]
    [SharedModule]
}

database PostgreSQL
cloud FlightProvider

[Screens] --> [Services]
[Services] --> [FlightModule]
[Services] --> [BillingModule]
[Services] --> [BookingModule]
[Services] --> [SharedModule]

[FlightModule] --> FlightProvider
[BillingModule] --> PostgreSQL
[BookingModule] --> PostgreSQL
[SharedModule] --> PostgreSQL

@enduml